version: '3'

networks:
  cicdnetwork:
    driver: bridge
  seleniumgrid:
    driver: bridge

services:
  seleniumhub:
    image: selenium/hub
    container_name: seleniumhub
    hostname: seleniumhub
    ports:
      - "4444:4444"
    networks:
      cicdnetwork:
        aliases:
          - seleniumhub
      seleniumgrid:
        aliases:
          - seleniumhub
    environment:
      - GRID_TIMEOUT=2
      - GRID_BROWSER_TIMEOUT=2
      - SE_OPTS=-timeout 120 -browserTimeout 120
    healthcheck:
        test: '/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444'
        interval: 15s
        timeout: 30s
        retries: 5
          
  firefox:
    image: selenium/node-firefox
    container_name: seleniumnodefirefox
    hostname: seleniumnodefirefox
    depends_on:
      - seleniumhub
    environment:
      - HUB_HOST=seleniumhub
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
    networks:
      seleniumgrid:
        aliases:
          - seleniumnodefirefox
    volumes:
      - /dev/shm:/dev/shm

  chrome:
    image: selenium/node-chrome
    container_name: seleniumnodechrome
    hostname: seleniumnodechrome
    depends_on:
      - seleniumhub
    environment:
      - HUB_HOST=seleniumhub
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
    networks:
      seleniumgrid:
        aliases:
          - seleniumnodechrome
    volumes:
      - /dev/shm:/dev/shm