version: '3'

networks:
  cicdnetwork:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db:
  nexus_data:
  jenkins_data:
  jenkins_home:

services:
  nexus:
    build: ./nexus
    container_name: nexus
    hostname: nexus
    image: nexus:mycicd
    ports:
      - "18081:8081"
    networks:
      - cicdnetwork
    volumes:
      - nexus_data:/nexus-data

  jenkins:
    build: ./jenkins
    container_name: jenkins
    hostname: jenkins
    image: jenkins:mycicd
    ports:
      - "18080:8080"
      - "50000:50000"
    networks:
      - cicdnetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /snap/bin/docker:/usr/bin/docker
      - jenkins_data:/var/lib/jenkins/
      - jenkins_home:/var/jenkins_home
    depends_on:
      - nexus
      - sonarqube
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432

  sonardb:
    networks:
      - cicdnetwork
    image: postgres:9.6
    container_name: sonardb
    hostname: sonardb
    ports:
      - "5432:5432"
    volumes:
      - sonarqube_db/:/var/lib/postgresql
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
     - POSTGRESQL_DB=sonar

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    hostname: sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
     - "19000:9000"
    networks:
      - cicdnetwork
    depends_on:
      - sonardb
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONAR_JDBC_PASSWORD=sonar
  
  nginx-proxy:
    build: ./nginx
    container_name: nginx-proxy
    hostname: nginx-proxy
    image: nginx:mycicd
    networks:
      - cicdnetwork
    ports:
      - "28080:8080"
      - "28081:8081"
      - "29000:9000"
    links:
      - jenkins
      - sonarqube
      - nexus